name: deploy-release
on: pull_request

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current ref
        uses: actions/checkout@v4

      - name: Build
        run: |
          make
          git status -s
