name: deploy-release
on:
  pull_request:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current ref
        uses: actions/checkout@v4

      - name: Install groff package
        run: |
          sudo apt install -y groff

      - name: Build
        run: make

      - name: Release my soul
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./resume.pdf
          asset_name: resume.pdf
          body: 'Released!'
