name: deploy-release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout current ref
        uses: actions/checkout@v4

      - name: Install groff package
        run: sudo apt install -y groff

      - name: Build
        run: make

      # - name: Use changelog.md as release body
      #   id: read_changelog
      #   shell: bash
      #   run: |
      #     r=$(cat ./changelog.md)
      #     r="${r//'%'/'%25'}"
      #     r="${r//$'\n'/'%0A'}"
      #     r="${r//$'\r'/'%0D'}"
      #     echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT

      - name: Use annotated tag message as release notes
        id: release_notes
        run: |
          echo "ref: $GITHUB_REF"
          message="$(git for-each-ref --format='%(contents:body)' $GITHUB_REF)"
          echo "RELEASE_NOTES=$message" >> $GITHUB_OUTPUT

      - name: Release my soul
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./resume.pdf
          asset_name: resume.pdf
          body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
