name: deploy-release
on: pull_request

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current refs
        uses: actions/checkout@v4

      - name: Build
        run: ls
