name: deploy-release
on: pull_request

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current ref
        uses: actions/checkout@v4

      - name: Install groff package
        run: |
          sudo apt remove -y groff-base
          sudo apt install -y groff

      - name: Build
        run: |
          dpkg -S $(command -v groff)
